export const TETROMINO_NEXT = "TETROMINO/NEXT";
export const TETROMINO_MOVE_DOWN = "TETROMINO/MOVE_DOWN";
export const TETROMINO_MOVE_LEFT = "TETROMINO/MOVE_LEFT";
export const TETROMINO_MOVE_RIGHT = "TETROMINO/MOVE_RIGHT";
export const TETROMINO_DROP = "TETROMINO/DROP";
export const TETROMINO_ROTATE = "TETROMINO/ROTATE";